spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/text?allowMultiQueries=true
    password: root
    username: root
server:
  port: 8080
  servlet:
    context-path: /
mybatis:
  mapper-locations: classpath:Mapper/*.xml

